### ISSUE TITLE
current version links are broken and previous version raises JNI error

### ISSUE THREAD

**Issue by abubelinha** [nomencurator/taxonaut#5]
As it says in main page:

> Current version is [3.1.11](https://github.com/nomencurator/taxonaut/releases/tag/3.1.11). [Executable jar file](https://github.com/nomencurator/taxonaut/releases/download/3.1.11/Taxonaut-3.1.11-jar-with-dependencies.jar) is available to try on any Java 8 environment

Both are broken links, and 3.1.11 does not apear in the realeases list (right menu).

Moreover, if I double-click the previous version (Taxonaut-3.1.10-jar-with-dependencies.jar) I get this error in a pop message:

```
Java Virtual Machine Launcher
Error: A JNI error has occurred, please check your installation and try again
```
I upgraded my Java version and now I get a different message:
```
Java Virtual Machine Launcher
A Java Exception has occurred
```

If I run from command line interface this is the output:
```
C:\downloads>java -jar Taxonaut-3.1.10-jar-with-dependencies.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/nomencurator/gui/swing/Taxonaut has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

```
This is my java version:
```
C:\downloads>java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)
```
What am I supposed to do?
Thanks
@abubelinha

**Comment by jmsytow** [comment]
Thanks for your interest.
The link was wrong, even no entity to be linked.  Right one created and linked appropriately.
3.1.10 was compiled for Java 11 or higher so it doesn't run with Java 8.  3.1.11 should work, please try.

**Comment by abubelinha** [comment]
Great, I see the link now.

I will try. Thanks !!

EDIT: it works, so I close the issue
